apiVersion: v1
kind: Service
metadata:
  name: e-commerce-frontend-nodeport
spec:
  type: NodePort
  selector:
    app: e-commerce-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
                   
