apiVersion: v1
kind: Service
metadata:
  name: e-commerce-backend-nodeport
spec:
  type: NodePort
  selector:
    app: e-commerce-frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000                      